export const FETCH_DATA_IF_NEDEED =  'FETCH_DATA_IF_NEDEED';
export const FETCH_DATA = 'FETCH_DATA';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS'; 
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE'; 
export const FETCH_MOIVES_IF_NEEDED = 'FETCH_MOIVES_IF_NEEDED';
export const FETCH_NEXT_MOIVES_IF_NEEDED = 'FETCH_NEXT_MOIVES_IF_NEEDED';